workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Apple Connect App Mgr
    environment:
      ios_signing:
        provisioning_profiles:
          - PumpkinPatch2
      vars:
        APP_STORE_APPLE_ID: 6749664824
        BUNDLE_ID: "com.huntergames.pumpkinpatch"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_VERSION: "2.0.16"
        BUILD_NUMBER: "21"
      node: v20.18.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          echo "=== Cleaning previous build ==="
          rm -rf dist/
          echo "=== Building web app for production ==="
          NODE_ENV=production npm run build
          echo "=== Build completed, checking output ==="
          ls -la dist/
      - name: Initialize Capacitor iOS platform
        script: |
          if [ ! -d "ios" ]; then
            echo "Creating iOS platform..."
            npx cap add ios
          else
            echo "iOS platform already exists, skipping initialization"
          fi
      - name: Sync Capacitor with built assets
        script: |
          echo "=== Cleaning Capacitor cache ==="
          npx cap clean ios
          echo "=== Syncing Capacitor with fresh build ==="
          npx cap sync ios --force
          echo "=== Verifying sync completed ==="
          ls -la ios/App/App/public/
          echo "=== Checking iOS bundle contents ==="
          grep -o "Settings" ios/App/App/public/assets/index-*.js | head -5 || echo "Settings not found in iOS bundle"
          echo "=== Verifying version in iOS bundle ==="
          grep "app-version\|build-number" ios/App/App/public/index.html || echo "Version info not synced"
      - name: Verify build output
        script: |
          echo "=== Checking build output ==="
          ls -la dist/public/
          echo "=== Checking HTML file ==="
          head -20 dist/public/index.html
          echo "=== Verifying Settings component in bundle ==="
          grep -o "Settings" dist/public/assets/index-*.js | head -5 || echo "Settings not found in bundle"
          echo "=== Checking version info ==="
          grep "app-version\|build-number" dist/public/index.html || echo "Version info not found"
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Update version and build number
        script: |
          echo "Setting version to $APP_VERSION and build number to $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/App/App/Info.plist
          echo "Verifying version numbers:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" ios/App/App/Info.plist
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        release_type: AFTER_APPROVAL
        copyright: 2025 Hunter Games