workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Apple Connect App Mgr
    environment:
      ios_signing:
        provisioning_profiles:
          - PumpkinPatch2
      vars:
        APP_STORE_APPLE_ID: 6749664824
        BUNDLE_ID: "com.huntergames.pumpkinpatch"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: v18.20.4
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        key_id: 7629KQWD3Z
        issuer_id: 27cc409c-83b9-4d67-a87f-99fc3d7c6f07
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_app_store: true
        release_type: AFTER_APPROVAL
        copyright: 2025 Hunter Games