-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvVNUC6XwMRzhNTzq
M3DjQkTwIP5NCa0CGfbO5fDRnUSgCgYIKoZIzj0DAQehRANCAASn6FdAnDitMM//
7MXnCg+krzRtYU01jV//oQQT+lVPy6BhMtug5kwgYE2UrrXQO9SPOI7PJNn4Z5JM
rZZCyS1Q
-----END PRIVATE KEY-----